dir: Electron-vanillaJS-HTML

packageJson: Electron-vanillaJS-HTML/package.json

articles:

 - Milestones: README.md
 - Overview: Electron-vanillaJS-HTML/readme.md

branches:

  - basic-electron-display
  - feature/implementTTS
